### PR TITLE
Update synopsys references to blackduck

### PR DESCRIPTION
**Pull request by devmehtasynopsys**
This PR updates the following for sierra changes:

- Update package names
- Update email recipients
- Update License
- Remove EULA
- Update dependency group names

### CODE REVIEW

**Comment by andrian-sevastyanov** [comment]
Looks like source code headers still contain "Copyright (c) 2024 Synopsys, Inc.".

**Comment by devmehtasynopsys** [comment]
> Looks like source code headers still contain "Copyright (c) 2024 Synopsys, Inc.".

As soon as this PR gets merged, https://github.com/blackducksoftware/integration-resources/pull/2, we can update all the headers at once by building the project, so to avoid manual work I will push one commit to update copyright, import statements and new version of library at the end before releasing.

**Comment by gopannabd** [comment]
@dterrysynopsys Should not regenerated code automatically apply rebranded names for packages? Would manual rename affect future generation of code?

**Comment by dterrysynopsys** [comment]
> @dterrysynopsys Should not regenerated code automatically apply rebranded names for packages? Would manual rename affect future generation of code?

I think we would need to change the generator, run a generation, and see what is left. I know we have some manual tweaks so changing some files by hand is likely necessary but yes, I agree we need to change the generation or we'll likely stomp on these changes. I'd start by looking at https://github.com/blackducksoftware/blackduck-common-apigen/blob/master/src/main/java/com/synopsys/integration/create/apigen/generation/finder/ClassNameManager.java#L20

**Review by andrian-sevastyanov — APPROVED** [review]

**Review by niravrsynopsys — APPROVED** [review]

**Review by DanaMaxfield — APPROVED** [review]

**Pull request merged**
